### PR TITLE
Fixed issue with IE11

### PR DESCRIPTION
**Pull request by 2ps**
The `url-polyfill` dependency v1.1.3 broke embedded hellosign in IE11.  This occurred
because the `_fromString` function required by `url-polyfill` could be placed on an object other
than the polyfilled `URL`, e.g. the polyfilled `URLSearchParams` from
`url-search-params-polyfill`.  [This issue has been addressed in
v1.1.5](https://github.com/lifaon74/url-polyfill/issues/43).

### CODE REVIEW

**Comment by nathanbuchar** [comment]
Thanks! We planned on doing an Embedded release later today, so we'll bundle this along with it.

**Comment by nathanbuchar** [comment]
We're going to close this PR, but update the package on our end. We require that all commits be signed and follow the [Conventional Commits spec](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)

I'll post here again once we've released

**Comment by nathanbuchar** [comment]
@2ps Embedded `v2.4.0` has been published to `@latest`. Please let us know if you have any further issues

**Comment by 2ps** [comment]
@nathanbuchar :  our sincere thanks.  On another note, is there a contributing doc about signing commits and commit specs that I missed?

**Comment by nathanbuchar** [comment]
[There is!](https://github.com/hellosign/hellosign-embedded/blob/master/.github/CONTRIBUTING.md), however it doesn't mention anything about commit signing at the moment.

**Pull request closed without merging**
